name: Python Cache

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/10 * * * *"

env:
  POETRY_VERSION: "1.2.2"
  PYTHON_VERSION: "3.10"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==${POETRY_VERSION}
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          # https://github.com/actions/setup-python#caching-packages-dependencies
          cache: poetry
      - name: Install Nox
        run: poetry install --only nox
      - name: Test with Nox
        run: poetry run nox -s test-3.11